### ISSUE TITLE
No such file or directory: './WEIGHTS/argument.pickle'

### ISSUE THREAD

**Issue by sofia0224** [tyui592/Real_Time_Helmet_Detection#1]
Traceback (most recent call last):
  File "evaluate.py", line 250, in <module>
    args = get_arguments()
  File "./Real_Time_Helmet_Detection/config.py", line 157, in get_arguments
    loaded_args = load_pickle(os.path.join(os.path.dirname(args.model_load), 'argument.pickle'))
  File "./Real_Time_Helmet_Detection/utils.py", line 15, in load_pickle
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './WEIGHTS/argument.pickle'

Can you add argument.pickle ?

**Comment by tyui592** [comment]
Thanks for reporting the error. 

I added [that file](https://github.com/tyui592/Real_Time_Helmet_Detection/releases/download/v0.0/argument.pickle) in the [v0.0 release](https://github.com/tyui592/Real_Time_Helmet_Detection/releases).
